BaseUrl: http://tracycodes.com
languageCode: en-us
title: Tracy L
paginate: 5
theme: casper
DisqusShortname: "tracycodes"
Copyright: "© 2015"
canonifyurls: true
params:
  description: "Thinking..."
  cover: "images/cover.jpg"
  author: "Tracy Livengood"
  authorlocation: "Menlo Park, CA"
  authorwebsite: "http://tracycodes.com"
  bio: "my bio"
  googleAnalyticsUserID: "UA-73157106-1"
  githubName: "tracycodes"
  twitterName: "tracycodes"
  linkedinName: "tracy-livengood-39b29210"
  hideHUGOSupport: true
